
package br.com.soaexpert.creditoservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import br.com.soaexpert.domain.Credito;
import br.com.soaexpert.domain.Empresa;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreditoService", targetNamespace = "http://soaexpert.com.br/CreditoService/")
@XmlSeeAlso({
    br.com.soaexpert.creditoservice.ObjectFactory.class,
    br.com.soaexpert.domain.ObjectFactory.class
})
public interface CreditoService {


    /**
     * 
     * @param empresa
     * @return
     *     returns br.com.soaexpert.domain.Credito
     * @throws VerificaCreditoSerasaFault_Exception
     */
    @WebMethod(action = "http://www.soaexpert.com.br/CreditoService/verificaCreditoSerasa")
    @WebResult(name = "credito", targetNamespace = "")
    @RequestWrapper(localName = "verificaCreditoSerasa", targetNamespace = "http://soaexpert.com.br/CreditoService/", className = "br.com.soaexpert.creditoservice.VerificaCreditoSerasa")
    @ResponseWrapper(localName = "verificaCreditoSerasaResponse", targetNamespace = "http://soaexpert.com.br/CreditoService/", className = "br.com.soaexpert.creditoservice.VerificaCreditoSerasaResponse")
    public Credito verificaCreditoSerasa(
        @WebParam(name = "empresa", targetNamespace = "")
        Empresa empresa)
        throws VerificaCreditoSerasaFault_Exception
    ;

    /**
     * 
     * @param empresa
     * @return
     *     returns br.com.soaexpert.domain.Credito
     * @throws VerificaCreditoSPCFault_Exception
     */
    @WebMethod(action = "http://www.soaexpert.com.br/CreditoService/verificaCreditoSPC")
    @WebResult(name = "credito", targetNamespace = "")
    @RequestWrapper(localName = "verificaCreditoSPC", targetNamespace = "http://soaexpert.com.br/CreditoService/", className = "br.com.soaexpert.creditoservice.VerificaCreditoSPC")
    @ResponseWrapper(localName = "verificaCreditoSPCResponse", targetNamespace = "http://soaexpert.com.br/CreditoService/", className = "br.com.soaexpert.creditoservice.VerificaCreditoSPCResponse")
    public Credito verificaCreditoSPC(
        @WebParam(name = "empresa", targetNamespace = "")
        Empresa empresa)
        throws VerificaCreditoSPCFault_Exception
    ;

    /**
     * 
     * @param empresa
     * @return
     *     returns br.com.soaexpert.domain.Credito
     * @throws VerificaCreditoCasasBahiaFault_Exception
     */
    @WebMethod(action = "http://www.soaexpert.com.br/CreditoService/verificaCreditoCasasBahia")
    @WebResult(name = "credito", targetNamespace = "")
    @RequestWrapper(localName = "verificaCreditoCasasBahia", targetNamespace = "http://soaexpert.com.br/CreditoService/", className = "br.com.soaexpert.creditoservice.VerificaCreditoCasasBahia")
    @ResponseWrapper(localName = "verificaCreditoCasasBahiaResponse", targetNamespace = "http://soaexpert.com.br/CreditoService/", className = "br.com.soaexpert.creditoservice.VerificaCreditoCasasBahiaResponse")
    public Credito verificaCreditoCasasBahia(
        @WebParam(name = "empresa", targetNamespace = "")
        Empresa empresa)
        throws VerificaCreditoCasasBahiaFault_Exception
    ;

}
