
package br.com.soaexpert.creditoservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CreditoService", targetNamespace = "http://soaexpert.com.br/CreditoService/", wsdlLocation = "file:/D:/FontesSOAExpert/circuitbreaker/circuitbreaker-camel-services/src/main/resources/contracts/CreditoService.wsdl")
public class CreditoService_Service
    extends Service
{

    private final static URL CREDITOSERVICE_WSDL_LOCATION;
    private final static WebServiceException CREDITOSERVICE_EXCEPTION;
    private final static QName CREDITOSERVICE_QNAME = new QName("http://soaexpert.com.br/CreditoService/", "CreditoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/FontesSOAExpert/circuitbreaker/circuitbreaker-camel-services/src/main/resources/contracts/CreditoService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREDITOSERVICE_WSDL_LOCATION = url;
        CREDITOSERVICE_EXCEPTION = e;
    }

    public CreditoService_Service() {
        super(__getWsdlLocation(), CREDITOSERVICE_QNAME);
    }

    public CreditoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREDITOSERVICE_QNAME, features);
    }

    public CreditoService_Service(URL wsdlLocation) {
        super(wsdlLocation, CREDITOSERVICE_QNAME);
    }

    public CreditoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREDITOSERVICE_QNAME, features);
    }

    public CreditoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CreditoService
     */
    @WebEndpoint(name = "CreditoServiceSOAP")
    public CreditoService getCreditoServiceSOAP() {
        return super.getPort(new QName("http://soaexpert.com.br/CreditoService/", "CreditoServiceSOAP"), CreditoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditoService
     */
    @WebEndpoint(name = "CreditoServiceSOAP")
    public CreditoService getCreditoServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://soaexpert.com.br/CreditoService/", "CreditoServiceSOAP"), CreditoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREDITOSERVICE_EXCEPTION!= null) {
            throw CREDITOSERVICE_EXCEPTION;
        }
        return CREDITOSERVICE_WSDL_LOCATION;
    }

}
