
package br.com.soaexpert.services.credito.verificacao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import br.com.soaexpert.domain.Credito;
import br.com.soaexpert.domain.Empresa;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreditoService", targetNamespace = "http://soaexpert.com.br/services/credito/verificacao")
@XmlSeeAlso({
    br.com.soaexpert.domain.ObjectFactory.class,
    br.com.soaexpert.services.credito.verificacao.ObjectFactory.class
})
public interface CreditoService {


    /**
     * 
     * @param empresa
     * @return
     *     returns br.com.soaexpert.domain.Credito
     * @throws VerificaCreditoCasasBahiaFault_Exception
     * @throws VerificaCreditoSPCFault_Exception
     * @throws VerificaCreditoSerasaFault_Exception
     */
    @WebMethod
    @WebResult(name = "credito", targetNamespace = "http://soaexpert.com.br/services/credito/verificacao")
    @RequestWrapper(localName = "verificaCredito", targetNamespace = "http://soaexpert.com.br/services/credito/verificacao", className = "br.com.soaexpert.services.credito.verificacao.VerificaCredito")
    @ResponseWrapper(localName = "verificaCreditoResponse", targetNamespace = "http://soaexpert.com.br/services/credito/verificacao", className = "br.com.soaexpert.services.credito.verificacao.VerificaCreditoResponse")
    public Credito verificaCredito(
        @WebParam(name = "empresa", targetNamespace = "http://soaexpert.com.br/services/credito/verificacao")
        Empresa empresa)
        throws VerificaCreditoCasasBahiaFault_Exception, VerificaCreditoSPCFault_Exception, VerificaCreditoSerasaFault_Exception
    ;

}
