
package br.com.soaexpert.services.credito.verificacao;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "verificaCreditoCasasBahiaFault", targetNamespace = "http://soaexpert.com.br/services/credito/verificacao")
public class VerificaCreditoCasasBahiaFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private VerificaCreditoCasasBahiaFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public VerificaCreditoCasasBahiaFault_Exception(String message, VerificaCreditoCasasBahiaFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public VerificaCreditoCasasBahiaFault_Exception(String message, VerificaCreditoCasasBahiaFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: br.com.soaexpert.services.credito.verificacao.VerificaCreditoCasasBahiaFault
     */
    public VerificaCreditoCasasBahiaFault getFaultInfo() {
        return faultInfo;
    }

}
