
package br.com.soaexpert.creditoservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import br.com.soaexpert.domain.Credito;
import br.com.soaexpert.domain.Empresa;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreditoService", targetNamespace = "http://soaexpert.com.br/CreditoService/")
@XmlSeeAlso({
    br.com.soaexpert.creditoservice.ObjectFactory.class,
    br.com.soaexpert.domain.ObjectFactory.class
})
public interface CreditoService {


    /**
     * 
     * @param empresa
     * @return
     *     returns br.com.soaexpert.domain.Credito
     * @throws VerificaCreditoSerasaFault_Exception
     * @throws VerificaCreditoCasasBahiaFault_Exception
     * @throws VerificaCreditoSPCFault_Exception
     */
    @WebMethod
    @WebResult(name = "credito", targetNamespace = "http://soaexpert.com.br/CreditoService/")
    @RequestWrapper(localName = "verificaCredito", targetNamespace = "http://soaexpert.com.br/CreditoService/", className = "br.com.soaexpert.creditoservice.VerificaCredito")
    @ResponseWrapper(localName = "verificaCreditoResponse", targetNamespace = "http://soaexpert.com.br/CreditoService/", className = "br.com.soaexpert.creditoservice.VerificaCreditoResponse")
    public Credito verificaCredito(
        @WebParam(name = "empresa", targetNamespace = "http://soaexpert.com.br/CreditoService/")
        Empresa empresa)
        throws VerificaCreditoCasasBahiaFault_Exception, VerificaCreditoSPCFault_Exception, VerificaCreditoSerasaFault_Exception
    ;

}
